name: onlyus
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  google_sign_in: ^6.3.0
  onesignal_flutter: ^5.3.3
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  share_plus: ^11.0.0
  firebase_database: ^11.3.6
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
